// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJZ9CIkK1XfL6TujS5-U6VtRM7Raibhg',
    appId: '1:577447468142:web:65f14f398b70fa7f191a7f',
    messagingSenderId: '577447468142',
    projectId: 'habito-app-4e2de',
    authDomain: 'habito-app-4e2de.firebaseapp.com',
    storageBucket: 'habito-app-4e2de.firebasestorage.app',
    measurementId: 'G-W1GK94BV9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFPcisKm2JqWSiWbGxuP-PZlqkPZRZ4g',
    appId: '1:577447468142:android:c345ebf81c8d700a191a7f',
    messagingSenderId: '577447468142',
    projectId: 'habito-app-4e2de',
    storageBucket: 'habito-app-4e2de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqLrE8VNwUwP3TN8XNJxKeXxdWgFT44w',
    appId: '1:577447468142:ios:77bea4d35d0a8354191a7f',
    messagingSenderId: '577447468142',
    projectId: 'habito-app-4e2de',
    storageBucket: 'habito-app-4e2de.firebasestorage.app',
    iosBundleId: 'com.habitobarberia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqLrE8VNwUwP3TN8XNJxKeXxdWgFT44w',
    appId: '1:577447468142:ios:6e9583198fa1f0e3191a7f',
    messagingSenderId: '577447468142',
    projectId: 'habito-app-4e2de',
    storageBucket: 'habito-app-4e2de.firebasestorage.app',
    iosBundleId: 'com.habitobarberia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTJZ9CIkK1XfL6TujS5-U6VtRM7Raibhg',
    appId: '1:577447468142:web:272c82e16116ca39191a7f',
    messagingSenderId: '577447468142',
    projectId: 'habito-app-4e2de',
    authDomain: 'habito-app-4e2de.firebaseapp.com',
    storageBucket: 'habito-app-4e2de.firebasestorage.app',
    measurementId: 'G-JQLEPY33CH',
  );
}
